### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'postMessage')

### ISSUE THREAD

**Issue by lionelgaillard** [microsoft/powerbi-client-angular#41]
Hello,

This error occurs if we destroy the `<powerbi-report />` approximately 1.5s after it was created.

## Scenario

A page "A" containing a `<powerbi-report />` component, and another another page "B" without the componenet.
(It would probably also happen by toggling the component with `ngIf`)

## Steps

- Open the page "A"
- Wait ~1.5s after the loading logo appeared, and leave page "A" for page "B".

## Expected

The component should be properly destroyed.

## Actual

`TypeError: Cannot read properties of null (reading 'postMessage')`

## Comment

The `ngx-powerbi` library seems to have the same issue:
https://github.com/ramandeep-singh-1983/ngx-powerbi/issues/48

**Comment by yurka1605** [comment]
This was recently fixed in the beta version 2.22.4 of the package https://www.npmjs.com/package/powerbi-client/v/2.22.4
I hope they fix it here

**Comment by lionelgaillard** [comment]
Hello,

I just updated `powerbi-client-angular` to version `3.0.5` and `powerbi-client` to version `2.22.4`, but the problem still exists.

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is an old issue, is it still relevant?

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.
